{% set name = "Dispenso" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookincubator/dispenso/archive/v{{ version }}.tar.gz
    sha256: 824afe8d0d36bfd9bc9b1cbe9be89e7f3ed642a3612766d1c99d5f8dfc647c63
    patches:
      - disable-install-gtest.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/lib/cmake/Dispenso-{{ version }}/DispensoConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\Dispenso-{{ version }}\\DispensoConfig.cmake exit 1  # [win]

about:
  home: https://github.com/facebookincubator/dispenso
  summary: 'The project provides high-performance concurrency, enabling highly parallel computation.'
  description: |
    Dispenso is a library for working with sets of tasks in parallel. It provides mechanisms for
    thread pools, task sets, parallel for loops, futures, pipelines, and more. Dispenso is a
    well-tested C++14 library designed to have minimal dependencies (some dependencies are required
    for the tests and benchmarks), and designed to be clean with compiler sanitizers (ASAN, TSAN).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookincubator/dispenso

extra:
  recipe-maintainers:
    - jeongseok-meta
